# -*- coding: utf-8 -*-
"""Fix Exploratory Data Analysis (EDA) .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qW1lgidqc9eu1RLLR2EXb2kpaMOVfm2G

## Menjalankan data tempat wisata

### Declaration of Library
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import RegexpTokenizer
import re
import string
import random
from PIL import Image
import requests
from io import BytesIO
import matplotlib.pyplot as plt
# %matplotlib inline

"""### Upload dataset"""

## Code ambil melalui file pribadi
from google.colab import files
uploaded = files.upload()

"""Kalau mau ambil dataset lewat link github bisa pakai code dibawah ini

### Load dataset
"""

## Load Dataset ulang nama file tourism

df = pd.read_csv('lokis (4).csv')
df

"""### Exploratory Data Analysis (EDA)"""

#Checking the shape of the file
df.shape

df.columns

# Informasi umum mengenai data
df.info()

varObjects = df.select_dtypes(include = ['object'])
varObjects

## Ubah type data dari object ke category
for col in varObjects.columns:
    df[col] = df[col].astype('category')
df.info()

# Statistik deskriptif untuk kolom-kolom numerik
df.describe(include='all')

# Memeriksa missing values
df.isnull().sum()

# mengecek apakah ada duplikat data sangatlah mudah menggunakan Pandas
# Bayangkan jika menggunakan Excel.
print(df.shape)
print("jumlah data yang duplikat", df.duplicated().sum())
df[df.duplicated() == True]

# Genre distribution
df['category'].value_counts().plot(x = 'category', y ='count', kind = 'bar', figsize = (10,5))

# Genre distribution
df['price'].value_counts().plot(x = 'price', y ='count', kind = 'bar', figsize = (10,5))

# Genre distribution
df['rating'].value_counts().plot(x = 'rating', y ='count', kind = 'bar', figsize = (10,5))

# Genre distribution
df['open hours'].value_counts().plot(x = 'open hours', y ='count', kind = 'bar', figsize = (10,5))

# Visual Python: Data Analysis > Sweetviz
!pip install sweetviz
# Visual Python: Data Analysis > Sweetviz
import sweetviz

## Code ini membantu untuk melihat telaah data pada masing-masing variabel pada data tempat wisata
# Visual Python: Data Analysis > Sweetviz
report = sweetviz.analyze([df, 'laporan_penelaahan_data'])
report.show_notebook()
report